// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAVvPyFeil_LMxOeeRnepe2JIKdf3B-mI',
    appId: '1:640358213318:web:cb692342d50d81be14d9c7',
    messagingSenderId: '640358213318',
    projectId: 'resumeai-1621d',
    authDomain: 'resumeai-1621d.firebaseapp.com',
    storageBucket: 'resumeai-1621d.firebasestorage.app',
    measurementId: 'G-J6TDH3Z83K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELcF1tN8vxB33EK0jB0q6nzWthvfAFzQ',
    appId: '1:640358213318:android:7f4ea73743735b2c14d9c7',
    messagingSenderId: '640358213318',
    projectId: 'resumeai-1621d',
    storageBucket: 'resumeai-1621d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVKHHvWlMT3gjt-r2cDo_sqPujzm1Y8Qg',
    appId: '1:640358213318:ios:3351c36a8bafb87514d9c7',
    messagingSenderId: '640358213318',
    projectId: 'resumeai-1621d',
    storageBucket: 'resumeai-1621d.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVKHHvWlMT3gjt-r2cDo_sqPujzm1Y8Qg',
    appId: '1:640358213318:ios:3351c36a8bafb87514d9c7',
    messagingSenderId: '640358213318',
    projectId: 'resumeai-1621d',
    storageBucket: 'resumeai-1621d.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAVvPyFeil_LMxOeeRnepe2JIKdf3B-mI',
    appId: '1:640358213318:web:68a334174192274c14d9c7',
    messagingSenderId: '640358213318',
    projectId: 'resumeai-1621d',
    authDomain: 'resumeai-1621d.firebaseapp.com',
    storageBucket: 'resumeai-1621d.firebasestorage.app',
    measurementId: 'G-ZSB4T380GL',
  );
}
